#!/bin/bash

JobNb=@JobNb

rm efficiency_cut_proba_208Tl.txt

root -l -b -q root_extract.cc\($JobNb,0.0278,\"208Tl\",0\)

for ((k=0;k<100;k+=5))

do

    l=$((10**9 * $k/100))e-9

    echo "test script 208Tl sigma = $l"

    root -l -b -q root_extract.cc\($JobNb,0.0278,\"208Tl\",0,0,1,$l,0\)


done
