#!/bin/bash



root -l -b -q root_extract.cc\(0.3,0.0278,\"0nubb\",0\)
root -l -b -q root_extract.cc\(0.3,0.0278,\"2nubb_2MeV\",0\)
root -l -b -q root_extract.cc\(0.3,0.0278,\"2nubb\",0\)
root -l -b -q root_extract.cc\(0.3,0.0278,\"208Tl\",0\)
root -l -b -q root_extract.cc\(0.3,0.0278,\"214Bi\",0\)
# root -l -b -q root_extract.cc\(0.3,0.0278,\"222Rn\",0\)
