void unnamed()
{
//=========Macro generated from canvas: c/c
//=========  (Mon Jul 20 11:15:09 2020) by ROOT version6.08/06
   TCanvas *c = new TCanvas("c", "c",67,55,1853,1025);
   gStyle->SetOptStat(0);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0.3,1,1);
   pad1->Draw();
   pad1->cd();
   pad1->Range(-0.25,-8.699719e+23,2.251351,1.203523e+25);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetTopMargin(0.06626506);
   pad1->SetBottomMargin(0.06741251);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameBorderMode(0);
   
   TH1F *hSe__1 = new TH1F("hSe__1","",3,0,2);
   hSe__1->SetBinContent(1,5.32384e+24);
   hSe__1->SetBinContent(2,5.32384e+24);
   hSe__1->SetBinContent(3,3.46448e+24);
   hSe__1->SetBinError(1,5.32384e+24);
   hSe__1->SetBinError(2,5.32384e+24);
   hSe__1->SetBinError(3,3.46448e+24);
   hSe__1->SetEntries(3);
   hSe__1->SetLineColor(0);
   hSe__1->SetLineWidth(2);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#339999");
   hSe__1->SetMarkerColor(ci);
   hSe__1->SetMarkerStyle(8);
   hSe__1->GetXaxis()->SetBinLabel(1,"No background");
   hSe__1->GetXaxis()->SetBinLabel(2,"Nominal");
   hSe__1->GetXaxis()->SetBinLabel(3,"Measured");
   hSe__1->GetXaxis()->SetNdivisions(110);
   hSe__1->GetXaxis()->SetLabelFont(42);
   hSe__1->GetXaxis()->SetLabelSize(0);
   hSe__1->GetXaxis()->SetTitleSize(0.05);
   hSe__1->GetXaxis()->SetTickLength(0.025);
   hSe__1->GetXaxis()->SetTitleFont(42);
   hSe__1->GetYaxis()->SetTitle("Best limit on T_{1/2} (y)");
   hSe__1->GetYaxis()->SetNdivisions(210);
   hSe__1->GetYaxis()->SetLabelFont(42);
   hSe__1->GetYaxis()->SetLabelSize(0.05);
   hSe__1->GetYaxis()->SetTitleSize(0.05);
   hSe__1->GetYaxis()->SetTickLength(0.015);
   hSe__1->GetYaxis()->SetTitleFont(42);
   hSe__1->GetZaxis()->SetLabelFont(42);
   hSe__1->GetZaxis()->SetLabelSize(0.035);
   hSe__1->GetZaxis()->SetTitleSize(0.035);
   hSe__1->GetZaxis()->SetTitleFont(42);
   hSe__1->Draw("P");
   
   TH1F *hNd__2 = new TH1F("hNd__2","",3,0,2);
   hNd__2->SetBinContent(1,2.10969e+24);
   hNd__2->SetBinContent(2,2.10969e+24);
   hNd__2->SetBinContent(3,1.57034e+24);
   hNd__2->SetBinError(1,2.10969e+24);
   hNd__2->SetBinError(2,2.10969e+24);
   hNd__2->SetBinError(3,1.57034e+24);
   hNd__2->SetEntries(3);
   hNd__2->SetLineColor(0);
   hNd__2->SetLineWidth(2);
   hNd__2->SetMarkerColor(2);
   hNd__2->SetMarkerStyle(8);
   hNd__2->GetXaxis()->SetBinLabel(1,"No background");
   hNd__2->GetXaxis()->SetBinLabel(2,"Nominal");
   hNd__2->GetXaxis()->SetBinLabel(3,"Measured");
   hNd__2->GetXaxis()->SetNdivisions(110);
   hNd__2->GetXaxis()->SetLabelFont(42);
   hNd__2->GetXaxis()->SetLabelSize(0.05);
   hNd__2->GetXaxis()->SetTitleSize(0.05);
   hNd__2->GetXaxis()->SetTickLength(0.025);
   hNd__2->GetXaxis()->SetTitleFont(42);
   hNd__2->GetYaxis()->SetTitle("Best limit on T_{1/2} (y)");
   hNd__2->GetYaxis()->SetNdivisions(110);
   hNd__2->GetYaxis()->SetLabelFont(42);
   hNd__2->GetYaxis()->SetLabelSize(0.05);
   hNd__2->GetYaxis()->SetTitleSize(0.05);
   hNd__2->GetYaxis()->SetTickLength(0.015);
   hNd__2->GetYaxis()->SetTitleFont(42);
   hNd__2->GetZaxis()->SetLabelFont(42);
   hNd__2->GetZaxis()->SetLabelSize(0.035);
   hNd__2->GetZaxis()->SetTitleSize(0.035);
   hNd__2->GetZaxis()->SetTitleFont(42);
   hNd__2->Draw("Psame");
   
   TLegend *leg = new TLegend(0.557,0.71,0.897,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hSe","^{82}Se sources, with field 25 G","lep");
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);

   ci = TColor::GetColor("#339999");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hNd","^{150}Nd sources, with field 25 G","lep");
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   pad1->Modified();
   c->cd();
  
// ------------>Primitives in pad: pad2
   TPad *pad2 = new TPad("pad2", "pad2",0,0.005,1,0.303);
   pad2->Draw();
   pad2->cd();
   pad2->Range(-0.25,2.172143,2.251351,4.042782);
   pad2->SetFillColor(0);
   pad2->SetBorderMode(0);
   pad2->SetBorderSize(2);
   pad2->SetTopMargin(0.02287);
   pad2->SetBottomMargin(0.1752648);
   pad2->SetFrameBorderMode(0);
   pad2->SetFrameBorderMode(0);
   
   TH1F *hSeBInf__3 = new TH1F("hSeBInf__3","",3,0,2);
   hSeBInf__3->SetBinContent(1,2.7);
   hSeBInf__3->SetBinContent(2,2.7);
   hSeBInf__3->SetBinContent(3,2.7);
   hSeBInf__3->SetBinError(1,2.7);
   hSeBInf__3->SetBinError(2,2.7);
   hSeBInf__3->SetBinError(3,2.7);
   hSeBInf__3->SetMinimum(2.5);
   hSeBInf__3->SetMaximum(4);
   hSeBInf__3->SetEntries(3);

   ci = TColor::GetColor("#339999");
   hSeBInf__3->SetLineColor(ci);
   hSeBInf__3->SetLineWidth(0);

   ci = TColor::GetColor("#339999");
   hSeBInf__3->SetMarkerColor(ci);
   hSeBInf__3->SetMarkerStyle(8);
   hSeBInf__3->GetXaxis()->SetBinLabel(1,"No background");
   hSeBInf__3->GetXaxis()->SetBinLabel(2,"Nominal");
   hSeBInf__3->GetXaxis()->SetBinLabel(3,"Measured");
   hSeBInf__3->GetXaxis()->SetNdivisions(110);
   hSeBInf__3->GetXaxis()->SetLabelFont(42);
   hSeBInf__3->GetXaxis()->SetLabelSize(0.17);
   hSeBInf__3->GetXaxis()->SetTitleSize(0.05);
   hSeBInf__3->GetXaxis()->SetTickLength(0.025);
   hSeBInf__3->GetXaxis()->SetTitleFont(42);
   hSeBInf__3->GetYaxis()->SetTitle("Energy (MeV)");
   hSeBInf__3->GetYaxis()->SetNdivisions(8);
   hSeBInf__3->GetYaxis()->SetLabelFont(42);
   hSeBInf__3->GetYaxis()->SetLabelSize(0.1);
   hSeBInf__3->GetYaxis()->SetTitleSize(0.1);
   hSeBInf__3->GetYaxis()->SetTickLength(0.015);
   hSeBInf__3->GetYaxis()->SetTitleOffset(0.5);
   hSeBInf__3->GetYaxis()->SetTitleFont(42);
   hSeBInf__3->GetZaxis()->SetLabelFont(42);
   hSeBInf__3->GetZaxis()->SetLabelSize(0.035);
   hSeBInf__3->GetZaxis()->SetTitleSize(0.035);
   hSeBInf__3->GetZaxis()->SetTitleFont(42);
   hSeBInf__3->Draw("P");
   
   TH1F *hNdBInf__4 = new TH1F("hNdBInf__4","",3,0,2);
   hNdBInf__4->SetBinContent(1,3.1);
   hNdBInf__4->SetBinContent(2,3.1);
   hNdBInf__4->SetBinContent(3,3.1);
   hNdBInf__4->SetBinError(1,3.1);
   hNdBInf__4->SetBinError(2,3.1);
   hNdBInf__4->SetBinError(3,3.1);
   hNdBInf__4->SetEntries(3);
   hNdBInf__4->SetLineColor(2);
   hNdBInf__4->SetLineWidth(0);
   hNdBInf__4->SetMarkerColor(2);
   hNdBInf__4->SetMarkerStyle(8);
   hNdBInf__4->GetXaxis()->SetBinLabel(1,"No background");
   hNdBInf__4->GetXaxis()->SetBinLabel(2,"Nominal");
   hNdBInf__4->GetXaxis()->SetBinLabel(3,"Measured");
   hNdBInf__4->GetXaxis()->SetNdivisions(110);
   hNdBInf__4->GetXaxis()->SetLabelFont(42);
   hNdBInf__4->GetXaxis()->SetLabelSize(0.05);
   hNdBInf__4->GetXaxis()->SetTitleSize(0.05);
   hNdBInf__4->GetXaxis()->SetTickLength(0.025);
   hNdBInf__4->GetXaxis()->SetTitleFont(42);
   hNdBInf__4->GetYaxis()->SetTitle("Energy (MeV)");
   hNdBInf__4->GetYaxis()->SetNdivisions(110);
   hNdBInf__4->GetYaxis()->SetLabelFont(42);
   hNdBInf__4->GetYaxis()->SetLabelSize(0.05);
   hNdBInf__4->GetYaxis()->SetTitleSize(0.05);
   hNdBInf__4->GetYaxis()->SetTickLength(0.015);
   hNdBInf__4->GetYaxis()->SetTitleFont(42);
   hNdBInf__4->GetZaxis()->SetLabelFont(42);
   hNdBInf__4->GetZaxis()->SetLabelSize(0.035);
   hNdBInf__4->GetZaxis()->SetTitleSize(0.035);
   hNdBInf__4->GetZaxis()->SetTitleFont(42);
   hNdBInf__4->Draw("Psame");
   
   TH1F *hSeBSup__5 = new TH1F("hSeBSup__5","",3,0,2);
   hSeBSup__5->SetBinContent(1,3.15);
   hSeBSup__5->SetBinContent(2,3.15);
   hSeBSup__5->SetBinContent(3,3.35);
   hSeBSup__5->SetBinError(1,3.15);
   hSeBSup__5->SetBinError(2,3.15);
   hSeBSup__5->SetBinError(3,3.35);
   hSeBSup__5->SetEntries(3);

   ci = TColor::GetColor("#339999");
   hSeBSup__5->SetLineColor(ci);
   hSeBSup__5->SetLineWidth(0);

   ci = TColor::GetColor("#339999");
   hSeBSup__5->SetMarkerColor(ci);
   hSeBSup__5->SetMarkerStyle(8);
   hSeBSup__5->GetXaxis()->SetBinLabel(1,"No background");
   hSeBSup__5->GetXaxis()->SetBinLabel(2,"Nominal");
   hSeBSup__5->GetXaxis()->SetBinLabel(3,"Measured");
   hSeBSup__5->GetXaxis()->SetNdivisions(110);
   hSeBSup__5->GetXaxis()->SetLabelFont(42);
   hSeBSup__5->GetXaxis()->SetLabelSize(0.05);
   hSeBSup__5->GetXaxis()->SetTitleSize(0.05);
   hSeBSup__5->GetXaxis()->SetTickLength(0.025);
   hSeBSup__5->GetXaxis()->SetTitleFont(42);
   hSeBSup__5->GetYaxis()->SetTitle("Energy (MeV)");
   hSeBSup__5->GetYaxis()->SetNdivisions(110);
   hSeBSup__5->GetYaxis()->SetLabelFont(42);
   hSeBSup__5->GetYaxis()->SetLabelSize(0.05);
   hSeBSup__5->GetYaxis()->SetTitleSize(0.05);
   hSeBSup__5->GetYaxis()->SetTickLength(0.015);
   hSeBSup__5->GetYaxis()->SetTitleFont(42);
   hSeBSup__5->GetZaxis()->SetLabelFont(42);
   hSeBSup__5->GetZaxis()->SetLabelSize(0.035);
   hSeBSup__5->GetZaxis()->SetTitleSize(0.035);
   hSeBSup__5->GetZaxis()->SetTitleFont(42);
   hSeBSup__5->Draw("Psame");
   
   TH1F *hNdBSup__6 = new TH1F("hNdBSup__6","",3,0,2);
   hNdBSup__6->SetBinContent(1,3.55);
   hNdBSup__6->SetBinContent(2,3.55);
   hNdBSup__6->SetBinContent(3,3.75);
   hNdBSup__6->SetBinError(1,3.55);
   hNdBSup__6->SetBinError(2,3.55);
   hNdBSup__6->SetBinError(3,3.75);
   hNdBSup__6->SetEntries(3);
   hNdBSup__6->SetLineColor(2);
   hNdBSup__6->SetLineWidth(0);
   hNdBSup__6->SetMarkerColor(2);
   hNdBSup__6->SetMarkerStyle(8);
   hNdBSup__6->GetXaxis()->SetBinLabel(1,"No background");
   hNdBSup__6->GetXaxis()->SetBinLabel(2,"Nominal");
   hNdBSup__6->GetXaxis()->SetBinLabel(3,"Measured");
   hNdBSup__6->GetXaxis()->SetNdivisions(110);
   hNdBSup__6->GetXaxis()->SetLabelFont(42);
   hNdBSup__6->GetXaxis()->SetLabelSize(0.05);
   hNdBSup__6->GetXaxis()->SetTitleSize(0.05);
   hNdBSup__6->GetXaxis()->SetTickLength(0.025);
   hNdBSup__6->GetXaxis()->SetTitleFont(42);
   hNdBSup__6->GetYaxis()->SetTitle("Energy (MeV)");
   hNdBSup__6->GetYaxis()->SetNdivisions(110);
   hNdBSup__6->GetYaxis()->SetLabelFont(42);
   hNdBSup__6->GetYaxis()->SetLabelSize(0.05);
   hNdBSup__6->GetYaxis()->SetTitleSize(0.05);
   hNdBSup__6->GetYaxis()->SetTickLength(0.015);
   hNdBSup__6->GetYaxis()->SetTitleFont(42);
   hNdBSup__6->GetZaxis()->SetLabelFont(42);
   hNdBSup__6->GetZaxis()->SetLabelSize(0.035);
   hNdBSup__6->GetZaxis()->SetTitleSize(0.035);
   hNdBSup__6->GetZaxis()->SetTitleFont(42);
   hNdBSup__6->Draw("Psame");
   TLine *line = new TLine(0.333,2.7,0.333,3.15);

   ci = TColor::GetColor("#339999");
   line->SetLineColor(ci);
   line->Draw();
   line = new TLine(1,2.7,1,3.15);

   ci = TColor::GetColor("#339999");
   line->SetLineColor(ci);
   line->Draw();
   line = new TLine(1.667,2.7,1.667,3.35);

   ci = TColor::GetColor("#339999");
   line->SetLineColor(ci);
   line->Draw();
   line = new TLine(0.333,3.1,0.333,3.55);
   line->SetLineColor(2);
   line->Draw();
   line = new TLine(1,3.1,1,3.55);
   line->SetLineColor(2);
   line->Draw();
   line = new TLine(1.667,3.1,1.667,3.75);
   line->SetLineColor(2);
   line->Draw();
   pad2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
