#!/bin/bash

#JobNb=@JobNb

#flreconstruct --pipeline "$CONFIG/Sensitivity/flreconstruct.conf" --input-file "/sps/nemo/scratch/simu/ylemiere/damned_sn_reco_/output_files.d/file_$JobNb.brio"  --output-file "$WORKDIR/Simulations/Sensitivity/150Nd/without_B/2nubb_2MeV/file_$JobNb.brio"
#cp sd_tree.root "$WORKDIR/Simulations/Sensitivity/150Nd/without_B/2nubb_2MeV/root_file_$JobNb.root"
#cp final_rate.txt "$WORKDIR/Simulations/Sensitivity/150Nd/without_B/2nubb_2MeV/event_number_$JobNb.txt"
